user/urls.py
from flask import (
    jsonify, request, Blueprint, render_template, make_response, session, g
)
from bson import objectid
from .db import (
    save_one, find_one
)
from .auth import (
    gen_hashpw, check_password, set_response_cookie, unset_reponse_cookie, check_input_valid, get_request_cookie,
    decode_token, create_token, get_user_id_name_email
)
from .decorators import login_required, logout_required
from .like import do_like, un_like

bp = Blueprint('user', __name__, template_folder='templates');


@bp.route("/", methods=["POST", "GET"])
@logout_required
def create_view():
    if request.method == "GET":
        return render_template("user/signup_form.html");

    username = request.form["username"];
    password = request.form["password"];
    email = request.form["email"];

    msg = check_input_valid(username, email, password);
    if msg != "success":
        return jsonify({"msg": msg});
    saved_id = save_one(username, gen_hashpw(password), email);
    return (jsonify({"msg": "success", "object": str(saved_id)}) if saved_id else jsonify({"msg": "fail"}));


@bp.route("login/", methods=["POST", "GET"])
@logout_required
def login():
    if request.method == "GET":
        return render_template("user/login_form.html");

    elif request.method == "POST":

        user = find_one({"email": request.form["email"]});
        if not user:
            return jsonify({"msg": "입력한 이메일 주소가 존재하지 않습니다."});
        if not check_password(user["password"], request.form["password"]):
            return jsonify({"msg": "비밀번호가 틀렸습니다."});

        user_token = create_token(user["_id"], user["username"], user["email"]);
        json_response = jsonify({"msg": "success", "access_token": user_token});
        response = set_response_cookie(json_response, user_token, user);
        return (response);


@bp.route("logout/", methods=["POST"])
@login_required
def logout():
    response = make_response(jsonify({"msg": "logout"}));
    response.set_cookie("Authorization", "", max_age=0);
    return response;


from .like import find_many as find_likes


@bp.route("info/", methods=["GET"])
@login_required
def detail():
    auth_token = get_request_cookie(request)
    if auth_token:
        user_id, user_name, user_email = get_user_id_name_email(request)
        user_likes = list(find_likes(user_id=user_id));
        print(user_likes)
        list(map(lambda el: el.update({"_id": str(el["_id"])}), user_likes));
        return jsonify({"_id": user_id, "email": user_email, "name": user_name, "likes": user_likes});
    else:
        return jsonify({"err": True, "msg": "invalid_token!"});


@bp.route("like/<lecture_id>/", methods=["GET"])
@login_required
def like_lecture(lecture_id):
    user_id, _, _ = get_user_id_name_email(request)
    print(user_id);
    ret = do_like(user_id, lecture_id);
    print(ret);
    if ret:
        return (jsonify({"msg": "success"}));
    return (jsonify({"msg": "failed", "err": True}));


@bp.route("unlike/<lecture_id>/", methods=["GET"])
@login_required
def unlike_lecture(lecture_id):
    user_id, _, _ = get_user_id_name_email(request)
    ret = un_like(user_id, lecture_id);
    print(ret);
    if ret:
        return (jsonify({"msg": "success"}));
    return (jsonify({"msg": "failed", "err": True}));

templates/base.html
<!DOCTYPE html>
<html lang="en">
<HEAD>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta property="og:title" content="">
	<meta property="og:content" content="">
	<meta property="og:image" content="">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet"> 
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../static/css/style.css"/>

	<script>
	{% block script %}
	{% endblock %}
	</script>
	<title>hanghae99 10</title>
</head>
<body>
	<main>
		<header>

			{% block header %}

            {% endblock %}
		</header>
		{% block content %}


        {% endblock %}
	</main>
</body>
</body>
</html>

templates/lecture_post.html
<!DOCTYPE html>
<html lang="en">
<HEAD>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta property="og:title" content="">
	<meta property="og:content" content="">
	<meta property="og:image" content="">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../static/css/style.css"/>
    <style>


    </style>
	<script>

	function input_lecture() {
        console.log("asd")
        let url = $("#url").val()
        let comment = $("#comment").val()

        if($("#frontend_checkbox").is(':checked')==false && $("#backend_checkbox").is(':checked')==false && $("#etc_checkbox").is(':checked') == false){
            alert("강의 카테고리를 한 가지 이상 선택해주세요")
        }
        else {

            let [fr, bk, etc] = [$("#frontend_checkbox").is(':checked'), $("#backend_checkbox").is(':checked'), $("#etc_checkbox").is(':checked')]
            $.ajax({
                type: 'POST',
                url: '/lecture',
                traditional : true,
                data: {url_give: url, comment_give: comment, front_give : fr, back_give : bk, etc_give : etc},
                success: function (response) {


                    if(response["msg"] == "등록 완료!"){
                        window.alert(response["msg"])
                        window.location.replace("{{ url_for("home") }}")
                    }else{
                        window.alert(response["msg"])
                    }
                },
                err: function (...err) {
                    console.log("실패")
                    alert(err);
                }
            });
        }
    }

    function input_lecture2() {
        let [fr, bk, etc] = [$("#frontend_checkbox").checked, $("#backend_checkbox").checked, $("#etc_checkbox").checked]
        return [fr, bk, etc]
    }


    function goPage() { location.href="/"; }


    </script>
    <title>좋강추</title>
</head>
<body>
<header>
    <div class="mytitle">
        <a href="/">
            <h1 class="logo">좋강추</h1>
        </a>

    </div>

</header>

<div class="wrapper3">

    <div class="form-floating mb-3">
        <input type="email" class="form-control" id="url" placeholder="name@example.com">
        <label for="floatingInput">URL을 붙여넣어주세요</label>
    </div>

    <p><br><br>카테고리를 1가지 이상 선택해주세요</p>
    <div class="input-group">

        <div class="form-check form-check-inline">
            <input style="cursor:pointer" class="form-check-input" type="checkbox" id="frontend_checkbox" value="front">
            <label style="cursor:pointer" class="form-check-label" for="frontend_checkbox">프론트엔드</label>
        </div>

        <div class="form-check form-check-inline">
            <input style="cursor:pointer" class="form-check-input" type="checkbox" id="backend_checkbox" value="back">
            <label style="cursor:pointer" class="form-check-label" for="backend_checkbox">백엔드</label>
        </div>

        <div class="form-check form-check-inline">
            <input style="cursor:pointer" class="form-check-input" type="checkbox" id="etc_checkbox" value="etc">
            <label style="cursor:pointer" class="form-check-label" for="etc_checkbox">기타(취업 등)</label>
        </div>

    </div>




    <div>
        <div class="form-floating">
            <textarea class="form-control" placeholder="Leave a comment here" id="comment"
                      style="height: 200px"></textarea>
            <label for="floatingTextarea2">이래서 추천해요</label>
        </div>
        <a>
            <button class="post" onclick="input_lecture()">추천하기</button>
        </a>
    </div>


</div>



<div id='footer_wrapper'>
        <div>
            <nav>
                <a href='https://github.com/hyjune92/jogangchoo' target='_blank'>Github</a>
            </nav>
            <br>
            <p>
                <span>항해99 6기 D반 10조</span><br/>
                <span>한지훈   |   강형근   |   황연준</span><br/>
                <span>Has No Copyright 2022. johgangchu. All Rights Are Yours.</span>
            </p>
        </div>
    </div>
    <footer></footer>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<HEAD>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="">
    <meta property="og:content" content="">
    <meta property="og:image" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Open+Sans:wght@400;600&display=swap"
          rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="../static/css/style.css"/>


    <script src={{ url_for("static", filename="js/main.js") }}></script>




    <script>
        login_status = ("{{ login_status }}")
        console.log("로그인 상태", "login_status", login_status, typeof(login_status))

        $(document).ready(function () {
            // 로그인 된 상태라면
            if (login_status == "True") {
                // '로그인'버튼에 is-hidden이라는 클래스를 추가한다
                console.log("로그인 버튼 감추기");
                $("#login_button").addClass("d-none");
            }
            // 로그인 안 된 상태라면
            else {
                console.log("마이페이지 버튼 감추기");

                $("#mypage_button").addClass("is-hidden");

            }
         });


    </script>
    <title>좋강추</title>
</head>

<body>
<header>
    <div class="mytitle">
        <a href="/">
            <h1 class="logo">좋강추</h1>
        </a>
        <div class="mini_nav">

            <div class="log-out">
                <a href="/login" id="login_button">로그인</a>
            </div>

        </div>
    </div>
</header>


<div class="wrapper2">

    <div class="input-group mb-3">

        <input type="text" class="form-control" placeholder="이메일" aria-label="Username"
               aria-describedby="basic-addon1">
    </div>


    <div class="input-group mb-3">

        <input type="text" class="form-control" placeholder="비밀번호" aria-label="Username"
               aria-describedby="basic-addon1">
    </div>

    <a href="/lecture/post">
        <button class="login">로그인</button>
    </a>

    <a href="/lecture/post">
        <button class="login">회원가입</button>
    </a>


</div>

      <div id='footer_wrapper'>
        <div>
            <nav>
                <a href='https://github.com/hyjune92/jogangchoo' target='_blank'>Github</a>
            </nav>
            <br>
            <p>
                <span>항해99 6기 D반 10조</span><br/>
                <span>한지훈   |   강형근   |   황연준</span><br/>
                <span>Has No Copyright 2022. johgangchu. All Rights Is Yours.</span>
            </p>
        </div>
    </div>
    <footer></footer>

</body>
</html>

templates/mypage.html
<!DOCTYPE html>
<html lang="en">
<HEAD>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="">
    <meta property="og:content" content="">
    <meta property="og:image" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Open+Sans:wght@400;600&display=swap"
          rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../static/css/style.css"/>

    <style>
        .mytitle {
            width: 100%;
            height: 250px;

            background-color : #1D1B1B;

            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        .mytitle > a > button {
            width: 150px;
            height: 50px;

            background-color: transparent;
            color: #EC4D36;

            border-radius: 50px;
            border: 1px solid #EC4D36;

            margin-top: 10px;
        }

        .mytitle > button:hover {
            border: 2px solid #EC4D36;
        }

        .logo {
            font-size: 90px;
            color: #EC4D36
        }


    </style>


    <script>
        login_status = ("{{ login_status }}")
        console.log("로그인 상태", "login_status", login_status, typeof(login_status))

        $(document).ready(function () {
            // 로그인 된 상태라면
            if (login_status == "True") {
                // '로그인'버튼에 is-hidden이라는 클래스를 추가한다
                console.log("로그인 버튼 감추기");
                $("#login_button").addClass("d-none");
            }
            // 로그인 안 된 상태라면
            else {
                console.log("마이페이지 버튼 감추기");

                $("#mypage_button").addClass("is-hidden");

            }
         });


    </script>
    <title>좋강추</title>
</head>

<body>
    <header>
        <div class="mytitle">
            <a href="/">
                <h1 class="logo">좋강추</h1>
            </a>
            <div class="mini_nav">
                <div class="log-out">
                    <a href="/mypage" id="logout_button">로그아웃</a></div>
            </div>
        </div>


    </header>

    <div id='footer_wrapper'>
        <div>
            <nav>
                <a href='https://github.com/hyjune92/jogangchoo' target='_blank'>Github</a>
            </nav>
            <br>
            <p>
                <span>항해99 6기 D반 10조</span><br/>
                <span>한지훈   |   강형근   |   황연준</span><br/>
                <span>Has No Copyright 2022. johgangchu. All Rights Is Yours.</span>
            </p>
        </div>
    </div>
    <footer></footer>

</body>
</html>

templates/user/asdasd.html
<!DOCTYPE html>
<html lang="en">
<HEAD>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="">
    <meta property="og:content" content="">
    <meta property="og:image" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Open+Sans:wght@400;600&display=swap"
          rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="../../static/css/style.css"/>


    <script>
        function signup_check() {
            let username = $("#username").val();
            let email = $("#email").val();
            let password = $("#password").val();
            let password_confirm = $("#password_confirm").val();

            if (email == "") {
                alert("이메일 입력해주세요!")
                $("#email").val().focus()
                return false;
            }
            if (username == "") {
                alert("사용자이름을 입력해주세요!")
                $("#email").val().focus()
                return false;
            }
            if(password == ""){
                alert("비밀번호를 입력해주세요!");
                $("#password").focus()
                return false;
            }
            if(password_confirm != password){
                alert("비밀번호가 일치하지 않습니다! 다시한번 확인해주세요!");
                $("#password_confirm").focus()
                return false;
            }
          return true
        }

            function signup() {
            if (signup_check()) {
                let username, email, password;
                [username, email, password] = [
                    $("#username").val(),
                    $("#email").val(),
                    $("#password").val()
                ];
                console.log(username, email, password);
                user_doc = {
                    username: username,
                    email: email,
                    password: password
                };
                $.ajax({
                    type: 'POST',
                    url: '/user/',
                    data: user_doc,
                    success: function (response) {
                        if (response["err"]) {
                            window.alert(response["msg"]);
                        } else {
                            window.location.replace("{{url_for("user.login")}}");
                            alert("회원가입이 완료되었습니다.")
                        }
                    },
                    err: function (...err) {
                        alert(err);
                    }
                });
            }
        }

        login_status = ("{{ login_status }}")
        console.log("로그인 상태", "login_status", login_status, typeof (login_status))

        $(document).ready(function () {
            // 로그인 된 상태라면
            if (login_status == "True") {
                // '로그인'버튼에 is-hidden이라는 클래스를 추가한다
                console.log("로그인 버튼 감추기");
                $("#login_button").addClass("d-none");
            }
            // 로그인 안 된 상태라면
            else {
                console.log("마이페이지 버튼 감추기");

                $("#mypage_button").addClass("is-hidden");

            }
        });
    </script>

    <title>좋강추</title>

</HEAD>

<header>

    <div class="mytitle">
        <a href="/">
            <h1 class="logo">좋강추</h1>
        </a>
        <div class="mini_nav">
            <div class="log-out">
                <a href="/login" id="login_button">로그인</a>
            </div>
        </div>

    </div>
</header>

<div class="wrapper2">
    <div class="input-group mb-3">
        <input id="email" type="text" class="form-control" placeholder="이메일" aria-label="Username"
               aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <input id="username" type="text" class="form-control" placeholder="이름" aria-label="Username"
               aria-describedby="basic-addon1">
    </div>

    <div class="input-group mb-3">

        <input id="password" type="password" class="form-control" placeholder="비밀번호" aria-label="Username"
               aria-describedby="basic-addon1">
    </div>

    <div class="input-group mb-3">

        <input type="password" class="form-control" placeholder="비밀번호 확인" aria-label="Username"
               aria-describedby="basic-addon1" id = "password_confirm">
    </div>


    <a>
        <button class="login" onclick="signup()">회원가입</button>
    </a>


</div>

<div id='footer_wrapper'>
    <div>
        <nav>
            <a href='https://github.com/hyjune92/jogangchoo' target='_blank'>Github</a>
        </nav>
        <br>
        <p>
            <span>항해99 6기 D반 10조</span><br/>
            <span>한지훈   |   강형근   |   황연준</span><br/>
            <span>Has No Copyright 2022. johgangchu. All Rights Are Yours.</span>
        </p>
    </div>
</div>
<footer></footer>

</body>
</html>

templates/user/signup_form.html
<!DOCTYPE html>
<html lang="en">
<HEAD>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="">
    <meta property="og:content" content="">
    <meta property="og:image" content="">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&family=Open+Sans:wght@400;600&display=swap"
          rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="../../static/css/style.css"/>


    <script>
        function signup() {
            let username, email, password;
            [username, email, password] = [
                $("#username").val(),
                $("#email").val(),
                $("#password").val()
            ];
            console.log(username, email, password);
            user_doc = {
                username: username,
                email: email,
                password: password
            };
            $.ajax({
                type: 'POST',
                url: '/user/',
                data: user_doc,
                success: function (response) {
                    if (response["err"]) {
                        window.alert(response["msg"]);
                    } else {
                        window.location.replace("{{url_for("user.login")}}");
                        alert("회원가입이 완료되었습니다.")
                    }
                },
                err: function (...err) {
                    alert(err);
                }
            });
        }


        login_status = ("{{ login_status }}")
        console.log("로그인 상태", "login_status", login_status, typeof (login_status))

        $(document).ready(function () {
            // 로그인 된 상태라면
            if (login_status == "True") {
                // '로그인'버튼에 is-hidden이라는 클래스를 추가한다
                console.log("로그인 버튼 감추기");
                $("#login_button").addClass("d-none");
            }
            // 로그인 안 된 상태라면
            else {
                console.log("마이페이지 버튼 감추기");

                $("#mypage_button").addClass("is-hidden");

            }
        });
    </script>

    <title>좋강추</title>

</HEAD>

<header>

    <div class="mytitle">
        <a href="/">
            <h1 class="logo">좋강추</h1>
        </a>
        <div class="mini_nav">
            <div class="log-out">
                <a href="/login" id="login_button">로그인</a>
            </div>
        </div>

    </div>
</header>

<div class="wrapper2">
    <div class="input-group mb-3">
        <input id="email" type="text" class="form-control" placeholder="이메일" aria-label="Username"
               aria-describedby="basic-addon1">
    </div>
    <div class="input-group mb-3">
        <input id="username" type="text" class="form-control" placeholder="이름" aria-label="Username"
               aria-describedby="basic-addon1">
    </div>

    <div class="input-group mb-3">

        <input id="password" type="text" class="form-control" placeholder="비밀번호" aria-label="Username"
               aria-describedby="basic-addon1">
    </div>

    <div class="input-group mb-3">

        <input type="text" class="form-control" placeholder="비밀번호 확인" aria-label="Username"
               aria-describedby="basic-addon1">
    </div>


    <a href="/lecture/post">
        <button class="login" onclick="signup()">회원가입</button>
    </a>


</div>

<div id='footer_wrapper'>
    <div>
        <nav>
            <a href='https://github.com/hyjune92/jogangchoo' target='_blank'>Github</a>
        </nav>
        <br>
        <p>
            <span>항해99 6기 D반 10조</span><br/>
            <span>한지훈   |   강형근   |   황연준</span><br/>
            <span>Has No Copyright 2022. johgangchu. All Rights Is Yours.</span>
        </p>
    </div>
</div>
<footer></footer>

</body>
</html>